apiVersion: v1
kind: Secret
metadata:
  name: flowise-secrets
type: Opaque
stringData:
  API_KEY: "your-api-key"
  POSTGRES_USER: "flowise_user"
  POSTGRES_PASSWORD: "flowise_password"
  POSTGRES_DB: "flowise_db"
