apiVersion: v1
kind: PersistentVolume
metadata:
  name: flowise-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/flowise"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowise-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
